### ISSUE TITLE
Markup/styles for original template?

### ISSUE THREAD

**Issue by iMerica** [schiehll/react-alert-template-basic#1]
Hi,

I've been using react-alert since v1.0.14 and I've now upgraded to the latest version (v3). Do you have the markup & styles for the original template (as seen on http://schiehll.github.io/react-alert/ ) ?

Thanks,

Michael

**Comment by iMerica** [comment]
Before on v1.014:
(cool material-ui looking design with icon and shadow)

<img width="346" alt="screen shot 2018-01-02 at 3 21 24 am" src="https://user-images.githubusercontent.com/487897/34477986-20d66716-ef6c-11e7-9124-821e27dfa995.png">

After upgrading:
:-/
<img width="352" alt="screen shot 2018-01-02 at 3 21 40 am" src="https://user-images.githubusercontent.com/487897/34477998-37c80d26-ef6c-11e7-898f-0eb0df8c4520.png">

**Comment by schiehll** [comment]
Hey @iMerica, nice to know that there's someone using it for this long 😄 

I've just publish a package with a template for the old look

https://github.com/schiehll/react-alert-template-oldschool-dark

It's only the dark theme. Feel free to create a new one with the white theme!
Also, it doesn't have the hover effect in the close icon since it uses inline styles. Hope it's ok.

**Comment by iMerica** [comment]
Awesome. Thank you!
